{"uid":"b4f458cf09379bc7","name":"Sign in with valid and invalid data","fullName":"vizsgaremek.test.test_conduit.TestSignInAndSignOut#test_sign_in_with_csv","historyId":"6aaaa2ab7bd6da5158247a1f43702aad","time":{"start":1682101206903,"stop":1682101268540,"duration":61637},"status":"failed","statusMessage":"AssertionError: assert 'Login failed!' == ''\n  + Login failed!","statusTrace":"self = <test_conduit.TestSignInAndSignOut object at 0x7ff2c83c4760>\n\n    @allure.id(\"TC-03\")\n    @allure.title(\"Sign in with valid and invalid data\")\n    def test_sign_in_with_csv(self):\n        wait = WebDriverWait(self.browser, 10)\n        for user in get_users_from_file():\n            if user[0].startswith('signin'):\n                use_case, username, email, password, expected_title, expected_description = user\n                signin(self.browser, email, password)\n                try:\n>                   logout_button = wait.until(EC.element_to_be_clickable((By.XPATH, \"//a[@active-class='active']\")))\n\nvizsgaremek/test/test_conduit.py:74: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"30a202177ddffe7f6346e4cf94fffa55\")>\nmethod = <function element_to_be_clickable.<locals>._predicate at 0x7ff2c82d9240>\nmessage = ''\n\n    def until(self, method, message: str = \"\"):\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            time.sleep(self._poll)\n            if time.monotonic() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: \nE       Stacktrace:\nE       #0 0x562eb9a0bfe3 <unknown>\nE       #1 0x562eb974ad36 <unknown>\nE       #2 0x562eb9787c4d <unknown>\nE       #3 0x562eb9787d61 <unknown>\nE       #4 0x562eb97c36a4 <unknown>\nE       #5 0x562eb97a88ed <unknown>\nE       #6 0x562eb97c1232 <unknown>\nE       #7 0x562eb97a8693 <unknown>\nE       #8 0x562eb977b03a <unknown>\nE       #9 0x562eb977c17e <unknown>\nE       #10 0x562eb99cddbd <unknown>\nE       #11 0x562eb99d1c6c <unknown>\nE       #12 0x562eb99db4b0 <unknown>\nE       #13 0x562eb99d2d63 <unknown>\nE       #14 0x562eb99a5c35 <unknown>\nE       #15 0x562eb99f6138 <unknown>\nE       #16 0x562eb99f62c7 <unknown>\nE       #17 0x562eb9a04093 <unknown>\nE       #18 0x7f9eab2a8b43 <unknown>\n\n/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/selenium/webdriver/support/wait.py:95: TimeoutException\n\nDuring handling of the above exception, another exception occurred:\n\nself = <test_conduit.TestSignInAndSignOut object at 0x7ff2c83c4760>\n\n    @allure.id(\"TC-03\")\n    @allure.title(\"Sign in with valid and invalid data\")\n    def test_sign_in_with_csv(self):\n        wait = WebDriverWait(self.browser, 10)\n        for user in get_users_from_file():\n            if user[0].startswith('signin'):\n                use_case, username, email, password, expected_title, expected_description = user\n                signin(self.browser, email, password)\n                try:\n                    logout_button = wait.until(EC.element_to_be_clickable((By.XPATH, \"//a[@active-class='active']\")))\n                    logout_button.click()\n                except:\n>                   assert get_error_title(self.browser) == expected_title\nE                   AssertionError: assert 'Login failed!' == ''\nE                     + Login failed!\n\nvizsgaremek/test/test_conduit.py:77: AssertionError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_xunit_setup_method_fixture_TestSignInAndSignOut","time":{"start":1682101205809,"stop":1682101206902,"duration":1093},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false}],"afterStages":[{"name":"_xunit_setup_method_fixture_TestSignInAndSignOut::0","time":{"start":1682101268553,"stop":1682101268610,"duration":57},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false}],"labels":[{"name":"as_id","value":"TC-03"},{"name":"parentSuite","value":"vizsgaremek.test"},{"name":"suite","value":"test_conduit"},{"name":"subSuite","value":"TestSignInAndSignOut"},{"name":"host","value":"fv-az797-833"},{"name":"thread","value":"3058-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"vizsgaremek.test.test_conduit"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"b4f458cf09379bc7.json","parameterValues":[]}