{"uid":"b13d789a463e6d5","name":"Sign in with valid and invalid data","fullName":"vizsgaremek.test.test_conduit.TestSignInAndSignOut#test_sign_in_with_csv","historyId":"6aaaa2ab7bd6da5158247a1f43702aad","time":{"start":1682228477412,"stop":1682228477412,"duration":0},"status":"broken","statusMessage":"FileNotFoundError: [Errno 2] No such file or directory: 'datasource_users.csv'","statusTrace":"self = <test_conduit.TestSignInAndSignOut object at 0x7f4a9b740a30>\n\n    @allure.id(\"TC-03\")\n    @allure.title(\"Sign in with valid and invalid data\")\n    def test_sign_in_with_csv(self):\n        wait = WebDriverWait(self.browser, 10)\n>       for user in get_users_from_file():\n\nvizsgaremek/test/test_conduit.py:71: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\n    def get_users_from_file():\n        #with open('vizsgaremek/test/datasource_users.csv', 'r', encoding='UTF-8') as datafile:\n>       with open('datasource_users.csv', 'r', encoding='UTF-8') as datafile:\nE       FileNotFoundError: [Errno 2] No such file or directory: 'datasource_users.csv'\n\nvizsgaremek/test/main_functions.py:35: FileNotFoundError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_xunit_setup_method_fixture_TestSignInAndSignOut","time":{"start":1682228476477,"stop":1682228477411,"duration":934},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false}],"afterStages":[{"name":"_xunit_setup_method_fixture_TestSignInAndSignOut::0","time":{"start":1682228477421,"stop":1682228477477,"duration":56},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false}],"labels":[{"name":"as_id","value":"TC-03"},{"name":"parentSuite","value":"vizsgaremek.test"},{"name":"suite","value":"test_conduit"},{"name":"subSuite","value":"TestSignInAndSignOut"},{"name":"host","value":"fv-az1030-985"},{"name":"thread","value":"3147-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"vizsgaremek.test.test_conduit"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"b13d789a463e6d5.json","parameterValues":[]}