{"uid":"1d51ed5d7df36427","name":"Sign up with invalid data","fullName":"vizsgaremek.test.test_conduit.TestSignUp#test_sign_up_with_csv_invalid","historyId":"db178a6f3c6e588115a95d6365ccc185","time":{"start":1682094561140,"stop":1682094561140,"duration":0},"status":"broken","statusMessage":"AttributeError: 'function' object has no attribute 'get'","statusTrace":"self = <test_conduit.TestSignUp object at 0x7fd965d88070>\nbrowser = <bound method TestSignUp.test_sign_up_with_csv_invalid of <test_conduit.TestSignUp object at 0x7fd965d88070>>\n\n    def setup_method(self, browser):\n        self.browser = browser\n        chrome_driver_config()\n>       self.browser.get('http://localhost:1667/#/register')\nE       AttributeError: 'function' object has no attribute 'get'\n\nvizsgaremek/test/test_conduit.py:27: AttributeError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_xunit_setup_method_fixture_TestSignUp","time":{"start":1682094561141,"stop":1682094561907,"duration":766},"status":"broken","statusMessage":"AttributeError: 'function' object has no attribute 'get'\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/_pytest/python.py\", line 907, in xunit_setup_method_fixture\n    _call_with_optional_argument(func, method)\n  File \"/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/_pytest/python.py\", line 785, in _call_with_optional_argument\n    func(arg)\n  File \"/home/runner/work/conduit/conduit/vizsgaremek/test/test_conduit.py\", line 27, in setup_method\n    self.browser.get('http://localhost:1667/#/register')\n","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":true,"hasContent":true}],"afterStages":[],"labels":[{"name":"as_id","value":"TC-02"},{"name":"parentSuite","value":"vizsgaremek.test"},{"name":"suite","value":"test_conduit"},{"name":"subSuite","value":"TestSignUp"},{"name":"host","value":"fv-az257-803"},{"name":"thread","value":"3068-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"vizsgaremek.test.test_conduit"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"1d51ed5d7df36427.json","parameterValues":[]}